---
# ==============================================================================
# Immich Role - Handlers
# ==============================================================================

- name: restart immich
  community.docker.docker_compose_v2:
    project_src: "{{ immich_compose_dir }}"
    state: present
    recreate: always
  become: yes
