---
# ==============================================================================
# Tandoor Role - Handlers
# ==============================================================================

- name: restart tandoor
  community.docker.docker_compose_v2:
    project_src: "{{ tandoor_compose_dir }}"
    state: present
    recreate: always
  become: yes
